#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx
RORFILE="/usr/share/nginx/html/404error.html"

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/channel/UC6gPYA10qDdFzMVQ3s8hYxQ;\n\t}\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

STRING="Hello World!"
FOUR="Ceci n'est pas une page"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"

echo "$FOUR" > "$ERRORFILE"
sed -i "37i\ $ERRORREDIRECT" "$FILE"

sed -i "37i\ $CUSTOMHEADER" "$FILE"
service nginx restart
