#!/usr/bin/env bash
#  uses ssh to connect to your server using 
#the private key ~/.ssh/school with the user ubuntu


# Define the server's IP address
SERVER_IP=107.22.146.212

# Use SSH to connect to the server with the specified private key
ssh -i ~/.ssh/school ubuntu@107.22.146.212
